name: CI Pipeline for SonarQube Analysis

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Désactive le clone superficiel pour une meilleure analyse

      # Étape 2: Configuration de JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'  # Vous pouvez choisir une autre distribution si nécessaire

      # Étape 3: Cache des packages SonarQube et Gradle
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Étape 4: Compilation du projet et exécution des tests unitaires
      - name: Build and run unit tests
        run: ./gradlew build

      # Étape 5: Analyse avec SonarQube
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token d'authentification SonarQube
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # URL de l'instance SonarQube
        run: |
          # Vérifiez que le fichier sonar-project.properties existe
          if [ ! -f sonar-project.properties ]; then
            echo "sonar.projectKey=inf8371_tp1" > sonar-project.properties
            echo "sonar.projectName=inf8371_tp1" >> sonar-project.properties
            echo "sonar.projectVersion=1.0" >> sonar-project.properties
            echo "sonar.sources=src" >> sonar-project.properties
            echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
          fi
          ./gradlew sonar --info -Dorg.gradle.jvmargs="-Xmx2g"