name: SonarQube CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run SonarQube analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=inf8371_tp1 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_dbfeb7e44bdbc2d826a714c501f92c91cad447d6