name: SonarQube CI

on:
  push:
    branches:
      - main  # Changez cette branche si vous travaillez sur une autre branche
  pull_request:
    branches:
      - main  # Changez cette branche si vous travaillez sur une autre branche

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run SonarQube analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=inf8371_tp1 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_049134b79724d72b3eb5ad3b17192b186bd375d6
