name: Build and Test SonarQube (Gradle)

on:
  push:
    branches: [ "master" ]     # or your default branch
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle Wrapper
        # On some systems, the Gradle wrapper may lose its execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # (Optional) If your Gradle project produces a ZIP distribution 
      # similar to how SonarQube does with Maven, you can upload it:
      - name: Upload distribution artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: sonarqube-dist
          path: build/distributions/*.zip
