name: SonarQube CI

on:
  push:
    branches:
      - master  # Changez cette branche si vous travaillez sur une autre branche
  pull_request:
    branches:
      - master  # Changez cette branche si vous travaillez sur une autre branche

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Build with Gradle
        run: ./gradlew build
