name: SonarQube CI

on:
  push:
    branches:
      - master  # Changez cette branche si vous travaillez sur une autre branche
  pull_request:
    branches:
      - master  # Changez cette branche si vous travaillez sur une autre branche

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run SonarQube analysis
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=inf8371_tp1 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_049134b79724d72b3eb5ad3b17192b186bd375d6

